### PR TITLE
* #209: Fixed wrong values format of literal_exactnumeric and literal…

### LINKED ISSUE #208: API Documentation: literal_double and literal_exactnumeric
The example values for the numeric literals in `virtual_schema_api.md` are misleading/outdated.

Please change the values:
* literal_double: Change `"1.234"` to `"1.2345000000000000e+02"`.
* literal_exactnumeric: Change `"12345"` to `"123.45"`.

### LINKED ISSUE #209: Some Numeric Literals Have Wrong Data Type
For some numeric literals the adapter changes the data type from exact to approximate (or vice versa) when generating the pushdown query.

To fix this, please change the format of the numeric literals in the generated pushdown query:
* A **literal_exactnumeric** should always be a number without an "E" in the pushdown query.
Broken example: For `0.000000000000000000000000000000000001` the adapter generates `1E-36`, but should generate `0.000000000000000000000000000000000001`.
* A **literal_double** should always be a number with an "E" in the pushdown query. The format should be `DecimalFormat("0.################E0")`.
Broken example: For `CAST(1 AS DOUBLE)` the adapter generates `1.0`, but should generate `1E0`. Notice, that the CAST does not appear in the pushdown request, instead this is just a literal_double.

Dialects:
* In addition to these changes, the Exasol dialect should always add a `CAST(... AS DOUBLE)` for literal_double. Otherwise some numbers like 1E0 get parsed as DECIMAL.
* Other dialects might require similar adaptions.

### PR DESCRIPTION
**Pull request by AnastasiiaSergienko**
Closes #209 
Closes #208

### CODE REVIEW

File: src/main/java/com/exasol/adapter/sql/SqlLiteralExactnumeric.java [hunk 1]
```diff
@@ -1,18 +1,26 @@
...
     public SqlLiteralExactnumeric(final BigDecimal value) {
         this.value = value;
     }
 
-    public BigDecimal getValue() {
-        return value;
+    /**
+     * Get a value of the exactnumeric converted to a plain string without E notation.
+     * <p>
+     * For example: 1E-36 becomes 0.00000000000000000000000000000000000
```
Comment (exanm) [inline src/main/java/com/exasol/adapter/sql/SqlLiteralExactnumeric.java:17]:
```suggestion
     * For example: 1E-36 becomes 0.000000000000000000000000000000000001
```

**Review by exanm — DISMISSED** [review]

File: src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java [hunk 2]
```diff
@@ -199,29 +198,44 @@ void testParseLiteralTimestamputc() {
...
-    void testParseLiteralExactNumeric() {
+    @ParameterizedTest
+    @CsvSource({ "1E-36, 0.000000000000000000000000000000000001", //
+            "12345, 12345", //
+            "3.456e11, 345600000000", //
+            "9.8e-4, 0.00098", //
+            "9.236E-19, 0.0000000000000000009236", //
+            "123.45, 123.45", //
+            "12345, 12345" //
+    })
```
Comment (exanm) [inline src/test/java/com/exasol/adapter/request/parser/PushDownSqlParserTest.java:228]: Maybe add 1E35 as an example for our biggest DECIMAL type.
