### PR TITLE
Fix of COUNT(*) returning NULL from an empty group by

### LINKED ISSUE #292: [L3-3596] COUNT(*) returns NULL from an empty group by
https://exasol.atlassian.net/browse/L3-3596

### LINKED ISSUE #297: Wrong handling of aggregate functions in HAVING statement
Query from empty virtual schema table returns empty result (instead of expected 1)

```
SELECT 1 FROM VST.TEST1 HAVING  max(COL1) is null;
```

### PR DESCRIPTION
**Pull request by Shmuma**
Closes #292 
Closes #297

### CODE REVIEW

**Comment by Shmuma** [comment]
> Engine team gave us the tip to also check for `HAVING` clauses.
> 
> ```java
> if (hasSingleGroupAggregation(select) && !hasAggregateFunction(selectList) &&  !hasAggregateFunction(having) {
> ```
> 
> Also, they pointed out that in a visitor `getChildren` should not be necessary. @Shmuma, contact @narmion for context please.

Regarding HAVING is a good point, will check.
New method `getChildren` is absolutely necessary, without it, it is not possible to traverse the tree properly.

File: src/main/java/com/exasol/adapter/sql/SqlStatementSelect.java [hunk 1]
```diff
@@ -276,4 +279,26 @@ public SqlStatementSelect build() {
             return new SqlStatementSelect(this);
         }
     }
+
+    @Override
+    public List<SqlNode> getChildren() {
+        // This method is not super efficient, but it is not used at the moment and needed
+        // only for consistency with SqlNode interface.
+        ArrayList<SqlNode> children = new ArrayList<>();
```
Comment (kaklakariada) [inline src/main/java/com/exasol/adapter/sql/SqlStatementSelect.java]:
```suggestion
        List<SqlNode> children = new ArrayList<>();
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]
General: please replace `Arrays.asList()` with `List.of()`

**Review by antonireus — APPROVED** [review]

**Review by kaklakariada — APPROVED** [review]
