### PR TITLE
#190: Fixed SELECTLIST_EXPRESSIONS documentation

### LINKED ISSUE #190: SELECTLIST_EXPRESSIONS
Please extend the documentation of the capability SELECTLIST_EXPRESSIONS by adding this:
This capability contains a subset of SELECTLIST_PROJECTION. It allows projections, if the select list contains an expression.

Moved from https://github.com/exasol/virtual-schema-common-java/issues/187

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #190

### CODE REVIEW

File: src/main/java/com/exasol/adapter/capabilities/MainCapability.java [hunk 1]
```diff
@@ -7,18 +7,17 @@
...
      */
     SELECTLIST_PROJECTION,
 
     /**
      * Support expressions in the select list; Additional capabilities are required depending on the expression.
-     *
+     * <p>
+     * This capability contains a subset of SELECTLIST_PROJECTION. It allows projections, if the select list contains an
+     * expression.
+     * </p>
```
Comment (exanm) [inline src/main/java/com/exasol/adapter/capabilities/MainCapability.java:20]: For consistency within the file:
```suggestion
     * <p>
     * Attention: This capability contains a subset of SELECTLIST_PROJECTION. It allows projections if the select list
     * contains an expression.
     * </p>
     *
```

**Review by exanm — DISMISSED** [review]

**Review by AnastasiiaSergienko — APPROVED** [review]
