### PR TITLE
bug/227: Fixed incomplete logs

### LINKED ISSUE #227: Logs incomplete
When logging the virtual schema flow, the logs are incomplete, as it doesn't log the first `getCapabilities` request.

How to reproduce:

1) Install a virtual schema with a logger:
```
CREATE VIRTUAL SCHEMA <SCHEMA>
	USING <ADAPTER_SCRIPT> 
	WITH
	CATALOG_NAME = '<CATALOG>'
	SCHEMA_NAME = '<SCHEMA>'
	CONNECTION_NAME = '<CONNECTION>'
	DEBUG_ADDRESS='<IP_ADDRESS>:3000' LOG_LEVEL='ALL'
	;
```
2) On a terminal console, open `netcat` on listening mode:
`nc -lkp 3000`
3) Execute a select query on the virtual schema
`SELECT * FROM <VIRTUAL_SCHEMA>.<VIRTUAL_TABLE>`
4) Check the logs in the console, the `getCapabilities` request is not logged

Related issues: https://github.com/itsallcode/junit5-system-extensions/issues/20

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #227

### CODE REVIEW

File: src/main/java/com/exasol/adapter/RequestDispatcher.java [hunk 1]
```diff
@@ -40,10 +40,10 @@ public static String adapterCall(final ExaMetadata metadata, final String rawReq
 
     private static String processAdapterCall(final ExaMetadata metadata, final String rawRequest)
             throws AdapterException {
-        logVersionInformation();
-        logRawRequest(rawRequest);
         final AdapterRequest adapterRequest = parseRequest(rawRequest);
         configureAdapterLoggingAccordingToRequestSettings(adapterRequest);
```
Comment (tkilias) [inline src/main/java/com/exasol/adapter/RequestDispatcher.java:44]: Hm, we have a bit of a chicken and egg problem. If parseRequest fails we don't get the raw request logged. Maybe we need separate the configuration of the remote log from parsing the request. However, I don't know what exactly parseRequest does.

Comment (tkilias) [reply src/main/java/com/exasol/adapter/RequestDispatcher.java:44]: Ok, I had a look into parseRequest and actually contains quite a lot of logic. So, logging the rawRequest before it would be nice. However, we could also say we log the rawRequest first to console, such that you can get it via Alter session script_ourput_redirect or via the database log. The database logs have the disadvantage that users don't have easy access. So, logging to console is good extension here.

**Review by tkilias — CHANGES_REQUESTED** [review]

**Review by tkilias — APPROVED** [review]

**Comment by jakobbraun** [comment]
I just tested it manually with the s3 virtual schema. Now logging works as expected.
